In [1]:
import numpy as np
import pandas as pd
from pandas.core.interchange.dataframe_protocol import DataFrame

Merging Two DataFrames

In [4]:
empoloyees = {
    'employee_id' : [1,2,3,4,5],
    'name' : ['Navneet','Rohan','Rahul','Raj','Abhishek'],
    'department'  : ['HR','IT','CS','Finance','HR']
}
df1 = pd.DataFrame(empoloyees)
df1

   employee_id      name department
0            1   Navneet         HR
1            2     Rohan         IT
2            3     Rahul         CS
3            4       Raj    Finance
4            5  Abhishek         HR

In [7]:
salaries = {
    'employee_id' : [1,2,3,6,7],
    'salary' : [30000,25000,20000,15000,10000],
    'bonus'  : [5000,7000,9000,11000,14000]
}
df2 = pd.DataFrame(salaries)
df2

   employee_id  salary  bonus
0            1   30000   5000
1            2   25000   7000
2            3   20000   9000
3            6   15000  11000
4            7   10000  14000

In [11]:
pd.merge(df1,df2,on ='employee_id', how='inner')

   employee_id     name department  salary  bonus
0            1  Navneet         HR   30000   5000
1            2    Rohan         IT   25000   7000
2            3    Rahul         CS   20000   9000

In [12]:
pd.merge(df1,df2,on ='employee_id', how='outer')

   employee_id      name department   salary    bonus
0            1   Navneet         HR  30000.0   5000.0
1            2     Rohan         IT  25000.0   7000.0
2            3     Rahul         CS  20000.0   9000.0
3            4       Raj    Finance      NaN      NaN
4            5  Abhishek         HR      NaN      NaN
5            6       NaN        NaN  15000.0  11000.0
6            7       NaN        NaN  10000.0  14000.0

In [13]:
pd.merge(df1,df2,on ='employee_id', how='left')

   employee_id      name department   salary   bonus
0            1   Navneet         HR  30000.0  5000.0
1            2     Rohan         IT  25000.0  7000.0
2            3     Rahul         CS  20000.0  9000.0
3            4       Raj    Finance      NaN     NaN
4            5  Abhishek         HR      NaN     NaN

In [14]:
pd.merge(df1,df2,on ='employee_id', how='right')

   employee_id     name department  salary  bonus
0            1  Navneet         HR   30000   5000
1            2    Rohan         IT   25000   7000
2            3    Rahul         CS   20000   9000
3            6      NaN        NaN   15000  11000
4            7      NaN        NaN   10000  14000

Concatination Two DataFrames

In [15]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [16]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [17]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [19]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [20]:
pd.concat([df1,df2], axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

Joining Of Two DataFrames

In [21]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [22]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [23]:
df2

   score
2     85
3     90
4     75

In [25]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0