In [1]:
import numpy as np
import pandas as pd

Creating a DataFrame -> Combination of multiple Series

In [2]:
data = {
    'Name':['john','navneet','rahul','priya'],
    'Age':[28,22,29,32],
    'City':['mumbai','delhi','noida','Mumbai'],
    'Salary':[65000,70000,28000,60000]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
data_list = [
    ['john',28,'New York', 65000],
    ['Navneet',23,'Delhi',30000],
    ['ivaann',26,'Gudgaon',20000],
    ['rohit',30,'Mumbai',30000]
]

In [5]:
df2 = pd.DataFrame(data_list)
df2

         0   1         2      3
0     john  28  New York  65000
1  Navneet  23     Delhi  30000
2   ivaann  26   Gudgaon  20000
3    rohit  30    Mumbai  30000

In [6]:
columns = ["name","age","city","salary"]

In [7]:
df2 = pd.DataFrame(data_list,columns = columns)
df2

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000
2   ivaann   26   Gudgaon   20000
3    rohit   30    Mumbai   30000

**Section and indexing of column**

In [8]:
df2

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000
2   ivaann   26   Gudgaon   20000
3    rohit   30    Mumbai   30000

In [9]:
df2['name']

0       john
1    Navneet
2     ivaann
3      rohit
Name: name, dtype: str

In [10]:
df2['city']

0    New York
1       Delhi
2     Gudgaon
3      Mumbai
Name: city, dtype: str

In [11]:
df2[['name','city']]

      name      city
0     john  New York
1  Navneet     Delhi
2   ivaann   Gudgaon
3    rohit    Mumbai

Creating a new column

In [12]:
df2['Designation'] = ['HR','IT','HR','Tech-Support']
#yaha pr jaise selction k time krte hain same wahi krenge but ab = lga kr values assign krenge, dhyan rahe values same honi cahiye jitne rows hain, wrna error aa jayega.

In [13]:
df2

      name  age      city  salary   Designation
0     john   28  New York   65000            HR
1  Navneet   23     Delhi   30000            IT
2   ivaann   26   Gudgaon   20000            HR
3    rohit   30    Mumbai   30000  Tech-Support

Removing Columns

In [14]:
df2.drop('Designation', axis=1)
#in dataframe agr axis nahi dete to axis 0 hota , jo ki horizontal hota hai too wo "Designation" ko horizontali check krta hai.

#.drop se main data se remove nahi hota bs ek copy deikhata hai.

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000
2   ivaann   26   Gudgaon   20000
3    rohit   30    Mumbai   30000

In [16]:
df2.drop('Designation', axis=1,inplace=True)

#inplace ka use krke hum isko original dataframe se bhi delete kr skte hain.

In [18]:
#Can we drop multiple column ?
#yes.
df2.drop(['city','age'], axis=1)

      name  salary
0     john   65000
1  Navneet   30000
2   ivaann   20000
3    rohit   30000

In [19]:
#delete rows
df2.drop(0, axis=0)

      name  age     city  salary
1  Navneet   23    Delhi   30000
2   ivaann   26  Gudgaon   20000
3    rohit   30   Mumbai   30000

In [20]:
df2

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000
2   ivaann   26   Gudgaon   20000
3    rohit   30    Mumbai   30000

Selecting Rows

In [21]:
df2

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000
2   ivaann   26   Gudgaon   20000
3    rohit   30    Mumbai   30000

In [22]:
df2.loc[0]
#.loc - location for rows

name          john
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [24]:
df2.loc[[0,1]]

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000

In [25]:
df2.iloc[3] #index location

name       rohit
age           30
city      Mumbai
salary     30000
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [26]:
df2.loc[[0,1]][['city','salary']]

       city  salary
0  New York   65000
1     Delhi   30000

In [31]:
df2.loc[[2,3]][['name','age']]

     name  age
2  ivaann   26
3   rohit   30

## **Conditional Selection**

In [38]:
df2

      name  age      city  salary
0     john   28  New York   65000
1  Navneet   23     Delhi   30000
2   ivaann   26   Gudgaon   20000
3    rohit   30    Mumbai   30000

In [39]:
df2[df2['age'] > 25]

     name  age      city  salary
0    john   28  New York   65000
2  ivaann   26   Gudgaon   20000
3   rohit   30    Mumbai   30000

In [41]:
df2[ ( df2['age'] > 25 ) & ( df2['city'] == 'Mumbai' ) ]

    name  age    city  salary
3  rohit   30  Mumbai   30000